def test_data
  @bachelorette_1 = Bachelorette.create!(name: "Hannah Brown", season_number: 15, description: "This one time, at band camp...")
  @bachelorette_2 = Bachelorette.create!(name: "Katie Thurston", season_number: 17, description: "She chose WHO?!")
  @bachelorette_3 = Bachelorette.create!(name: "Michelle Young", season_number: 18, description: "She's a teacher!")
  @contestant_1 = @bachelorette_1.contestants.create!(name: "John Paul Jones", age: 25, hometown: "New York City")
  @contestant_2 = @bachelorette_1.contestants.create!(name: "Tyler Cameron", age: 27, hometown: "Jupiter, Florida")
  @contestant_3 = @bachelorette_2.contestants.create!(name: "Joe Coleman", age: 28, hometown: "Minneapolis, Minnesota")
  @contestant_4 = @bachelorette_2.contestants.create!(name: "Nate Coleman", age: 27, hometown: "Minneapolis, Minnesota")
  @contestant_5 = @bachelorette_3.contestants.create!(name: "Brandon Jones", age: 28, hometown: "Portland, Oregon")
  @contestant_6 = @bachelorette_3.contestants.create!(name: "Clayton Echard", age: 28, hometown: "Eureka, Missouri")
  @outing_1 = Outing.create!(name: "Skydiving", location: "New York City", date: "2021-09-01", time: "12:00:00")
  @outing_2 = Outing.create!(name: "Hot Air Balloon Ride", location: "New York City", date: "2021-09-02", time: "12:00:00")
  @outing_3 = Outing.create!(name: "Helicopter Ride", location: "New York City", date: "2021-09-03", time: "12:00:00")
  @outing_4 = Outing.create!(name: "Beach Picnic", location: "San Diego", date: "2021-09-04", time: "12:00:00")
  @outing_5 = Outing.create!(name: "Dinner", location: "San Diego", date: "2021-09-05", time: "12:00:00")
  @outing_6 = Outing.create!(name: "Hiking", location: "San Diego", date: "2021-09-06", time: "12:00:00")
  @contestant_outing_1 = ContestantOuting.create!(contestant_id: @contestant_1.id, outing_id: @outing_1.id)
  @contestant_outing_2 = ContestantOuting.create!(contestant_id: @contestant_2.id, outing_id: @outing_1.id)
  @contestant_outing_3 = ContestantOuting.create!(contestant_id: @contestant_3.id, outing_id: @outing_2.id)
  @contestant_outing_4 = ContestantOuting.create!(contestant_id: @contestant_4.id, outing_id: @outing_2.id)
end